@startuml

title __LOW-LEVEL-DESIGN-CODES's Class Diagram__\n

  namespace designPatterns.creational.abstract_factory {
    class designPatterns.creational.abstract_factory.LuxuryVehicle1 {
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    class designPatterns.creational.abstract_factory.LuxuryVehicle2 {
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    class designPatterns.creational.abstract_factory.LuxuryVehicleFactory {
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    class designPatterns.creational.abstract_factory.Main {
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    class designPatterns.creational.abstract_factory.OrdinaryVehicle1 {
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    class designPatterns.creational.abstract_factory.OrdinaryVehicle2 {
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    class designPatterns.creational.abstract_factory.OrdinaryVehicleFactory {
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    interface designPatterns.creational.abstract_factory.Vehicle {
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    interface designPatterns.creational.abstract_factory.VehicleFactory {
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    class designPatterns.creational.abstract_factory.VehicleFactoryProducer {
    }
  }
  

  namespace designPatterns.creational.builder {
    class designPatterns.creational.builder.Director {
    }
  }
  

  namespace designPatterns.creational.builder {
    class designPatterns.creational.builder.EngineeringStudentBuilder {
    }
  }
  

  namespace designPatterns.creational.builder {
    class designPatterns.creational.builder.MBAStudentBuilder {
    }
  }
  

  namespace designPatterns.creational.builder {
    class designPatterns.creational.builder.Main {
    }
  }
  

  namespace designPatterns.creational.builder {
    class designPatterns.creational.builder.Student {
    }
  }
  

  namespace designPatterns.creational.builder {
    abstract class designPatterns.creational.builder.StudentBuilder {
    }
  }
  

  namespace designPatterns.creational.factory {
    class designPatterns.creational.factory.Main {
    }
  }
  

  namespace designPatterns.creational.factory {
    class designPatterns.creational.factory.Rectangle {
    }
  }
  

  namespace designPatterns.creational.factory {
    interface designPatterns.creational.factory.Shape {
    }
  }
  

  namespace designPatterns.creational.factory {
    class designPatterns.creational.factory.ShapeFactory {
    }
  }
  

  namespace designPatterns.creational.factory {
    class designPatterns.creational.factory.Square {
    }
  }
  

  namespace designPatterns.solid.D {
    class designPatterns.solid.D.Main {
    }
  }
  

  namespace designPatterns.solid.I {
    interface designPatterns.solid.I.ChefInterface {
    }
  }
  

  namespace designPatterns.solid.I {
    class designPatterns.solid.I.Main {
    }
  }
  

  namespace designPatterns.solid.I {
    interface designPatterns.solid.I.WaiterInterface {
    }
  }
  

  namespace designPatterns.solid.I {
    interface designPatterns.solid.I.WrongEmployeeInterface {
    }
  }
  

  namespace designPatterns.solid.L {
    class designPatterns.solid.L.Main {
    }
  }
  

  namespace designPatterns.solid.L {
    namespace correct {
      class designPatterns.solid.L.correct.Bicycle {
      }
    }
  }
  

  namespace designPatterns.solid.L {
    namespace correct {
      class designPatterns.solid.L.correct.Car {
      }
    }
  }
  

  namespace designPatterns.solid.L {
    namespace correct {
      class designPatterns.solid.L.correct.EngineVehicle {
      }
    }
  }
  

  namespace designPatterns.solid.L {
    namespace correct {
      class designPatterns.solid.L.correct.Vehicle {
      }
    }
  }
  

  namespace designPatterns.solid.L {
    namespace wrong {
      class designPatterns.solid.L.wrong.Bicycle {
      }
    }
  }
  

  namespace designPatterns.solid.L {
    namespace wrong {
      class designPatterns.solid.L.wrong.Car {
      }
    }
  }
  

  namespace designPatterns.solid.L {
    namespace wrong {
      class designPatterns.solid.L.wrong.MotorCycle {
      }
    }
  }
  

  namespace designPatterns.solid.L {
    namespace wrong {
      class designPatterns.solid.L.wrong.Vehicle {
      }
    }
  }
  

  namespace designPatterns.solid.o {
    class designPatterns.solid.o.DatabaseInvoiceDao {
    }
  }
  

  namespace designPatterns.solid.o {
    class designPatterns.solid.o.FileInvoiceDao {
    }
  }
  

  namespace designPatterns.solid.o {
    interface designPatterns.solid.o.InvoiceDao {
    }
  }
  

  namespace designPatterns.solid.o {
    class designPatterns.solid.o.Main {
    }
  }
  

  namespace designPatterns.solid.s {
    class designPatterns.solid.s.Invoice {
    }
  }
  

  namespace designPatterns.solid.s {
    class designPatterns.solid.s.InvoiceDao {
    }
  }
  

  namespace designPatterns.solid.s {
    class designPatterns.solid.s.InvoicePrinter {
    }
  }
  

  namespace designPatterns.solid.s {
    class designPatterns.solid.s.Main {
    }
  }
  

  namespace designPatterns.solid.s {
    class designPatterns.solid.s.Marker {
    }
  }
  

  namespace problems.Apply_Coupon {
    abstract class problems.Apply_Coupon.CouponDecorator {
    }
  }
  

  namespace problems.Apply_Coupon {
    class problems.Apply_Coupon.Item1 {
    }
  }
  

  namespace problems.Apply_Coupon {
    class problems.Apply_Coupon.Item2 {
    }
  }
  

  namespace problems.Apply_Coupon {
    class problems.Apply_Coupon.Main {
    }
  }
  

  namespace problems.Apply_Coupon {
    class problems.Apply_Coupon.PercentageCouponDecorator {
    }
  }
  

  namespace problems.Apply_Coupon {
    abstract class problems.Apply_Coupon.Product {
    }
  }
  

  namespace problems.Apply_Coupon {
    enum ProductType {
    }
  }
  

  namespace problems.Apply_Coupon {
    class problems.Apply_Coupon.ShoppingCart {
    }
  }
  

  namespace problems.Apply_Coupon {
    class problems.Apply_Coupon.TypeCouponDecorator {
    }
  }
  

  namespace problems.Concurrency_Control_in_Distributed_Systems {
    class problems.Concurrency_Control_in_Distributed_Systems.Main {
    }
  }
  

  namespace problems.HashMap {
    class problems.HashMap.CustomHashMap {
    }
  }
  

  namespace problems.HashMap {
    class problems.HashMap.Main {
    }
  }
  

  namespace problems.MVC {
    class problems.MVC.Main {
    }
  }
  

  namespace problems.Null_Object_Pattern {
    class problems.Null_Object_Pattern.Car {
    }
  }
  

  namespace problems.Null_Object_Pattern {
    class problems.Null_Object_Pattern.Main {
    }
  }
  

  namespace problems.Null_Object_Pattern {
    class problems.Null_Object_Pattern.NullObject {
    }
  }
  

  namespace problems.Null_Object_Pattern {
    interface problems.Null_Object_Pattern.Vehicle {
    }
  }
  

  namespace problems.Online_Auction_System {
    class problems.Online_Auction_System.AuctionMediator {
    }
  }
  

  namespace problems.Online_Auction_System {
    class problems.Online_Auction_System.Bidder {
    }
  }
  

  namespace problems.Online_Auction_System {
    interface problems.Online_Auction_System.Colleague {
    }
  }
  

  namespace problems.Online_Auction_System {
    class problems.Online_Auction_System.Main {
    }
  }
  

  namespace problems.Online_Auction_System {
    interface problems.Online_Auction_System.Mediator {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.Address {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.CardPaymentMode {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.Cart {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.Inventory {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.Invoice {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.Main {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.NearestWarehouseSelectionStrategy {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.Order {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.OrderController {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    enum OrderStatus {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.Payment {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    interface problems.Order_Inventory_Management_Sysyem_Zepto.PaymentMode {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.Product {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.ProductCategory {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.ProductDeliverySystem {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.UPIPaymentMode {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.User {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.UserController {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.Warehouse {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    class problems.Order_Inventory_Management_Sysyem_Zepto.WarehouseController {
    }
  }
  

  namespace problems.Order_Inventory_Management_Sysyem_Zepto {
    abstract class problems.Order_Inventory_Management_Sysyem_Zepto.WarehouseSelectionStrategy {
    }
  }
  

  namespace problems.Undo_Redo {
    class problems.Undo_Redo.AirConditioner {
    }
  }
  

  namespace problems.Undo_Redo {
    interface problems.Undo_Redo.ICommand {
    }
  }
  

  namespace problems.Undo_Redo {
    class problems.Undo_Redo.Main {
    }
  }
  

  namespace problems.Undo_Redo {
    class problems.Undo_Redo.RemoteController {
    }
  }
  

  namespace problems.Undo_Redo {
    class problems.Undo_Redo.TurnOffACCommand {
    }
  }
  

  namespace problems.Undo_Redo {
    class problems.Undo_Redo.TurnOnACCommand {
    }
  }
  

  designPatterns.creational.abstract_factory.LuxuryVehicle1 .up.|> designPatterns.creational.abstract_factory.Vehicle
  designPatterns.creational.abstract_factory.LuxuryVehicle2 .up.|> designPatterns.creational.abstract_factory.Vehicle
  designPatterns.creational.abstract_factory.LuxuryVehicleFactory .up.|> designPatterns.creational.abstract_factory.VehicleFactory
  designPatterns.creational.abstract_factory.OrdinaryVehicle1 .up.|> designPatterns.creational.abstract_factory.Vehicle
  designPatterns.creational.abstract_factory.OrdinaryVehicle2 .up.|> designPatterns.creational.abstract_factory.Vehicle
  designPatterns.creational.abstract_factory.OrdinaryVehicleFactory .up.|> designPatterns.creational.abstract_factory.VehicleFactory
  designPatterns.creational.builder.Director o-- designPatterns.creational.builder.StudentBuilder : studentBuilder
  designPatterns.creational.builder.EngineeringStudentBuilder -up-|> designPatterns.creational.builder.StudentBuilder
  designPatterns.creational.builder.MBAStudentBuilder -up-|> designPatterns.creational.builder.StudentBuilder
  designPatterns.creational.factory.Rectangle .up.|> designPatterns.creational.factory.Shape
  designPatterns.creational.factory.Square .up.|> designPatterns.creational.factory.Shape
  designPatterns.solid.L.correct.Bicycle -up-|> designPatterns.solid.L.correct.Vehicle
  designPatterns.solid.L.correct.Car -up-|> designPatterns.solid.L.correct.EngineVehicle
  designPatterns.solid.L.correct.EngineVehicle -up-|> designPatterns.solid.L.correct.Vehicle
  designPatterns.solid.L.wrong.Bicycle -up-|> designPatterns.solid.L.wrong.Vehicle
  designPatterns.solid.L.wrong.Car -up-|> designPatterns.solid.L.wrong.Vehicle
  designPatterns.solid.L.wrong.MotorCycle -up-|> designPatterns.solid.L.wrong.Vehicle
  designPatterns.solid.o.DatabaseInvoiceDao .up.|> designPatterns.solid.o.InvoiceDao
  designPatterns.solid.o.FileInvoiceDao .up.|> designPatterns.solid.o.InvoiceDao
  designPatterns.solid.s.Invoice o-- designPatterns.solid.s.Marker : marker
  designPatterns.solid.s.InvoiceDao o-- designPatterns.solid.s.Invoice : invoice
  designPatterns.solid.s.InvoicePrinter o-- designPatterns.solid.s.Invoice : invoice
  problems.Apply_Coupon.CouponDecorator -up-|> problems.Apply_Coupon.Product
  problems.Apply_Coupon.Item1 -up-|> problems.Apply_Coupon.Product
  problems.Apply_Coupon.Item2 -up-|> problems.Apply_Coupon.Product
  problems.Apply_Coupon.PercentageCouponDecorator -up-|> problems.Apply_Coupon.CouponDecorator
  problems.Apply_Coupon.PercentageCouponDecorator o-- problems.Apply_Coupon.Product : product
  problems.Apply_Coupon.Product o-- problems.Apply_Coupon.ProductType : type
  problems.Apply_Coupon.TypeCouponDecorator -up-|> problems.Apply_Coupon.CouponDecorator
  problems.Apply_Coupon.TypeCouponDecorator o-- problems.Apply_Coupon.Product : product
  problems.Apply_Coupon.TypeCouponDecorator o-- problems.Apply_Coupon.ProductType : type
  problems.Null_Object_Pattern.Car .up.|> problems.Null_Object_Pattern.Vehicle
  problems.Null_Object_Pattern.NullObject .up.|> problems.Null_Object_Pattern.Vehicle
  problems.Online_Auction_System.AuctionMediator .up.|> problems.Online_Auction_System.Mediator
  problems.Online_Auction_System.Bidder .up.|> problems.Online_Auction_System.Colleague
  problems.Online_Auction_System.Bidder o-- problems.Online_Auction_System.Mediator : auctionMediator
  problems.Order_Inventory_Management_Sysyem_Zepto.CardPaymentMode .up.|> problems.Order_Inventory_Management_Sysyem_Zepto.PaymentMode
  problems.Order_Inventory_Management_Sysyem_Zepto.NearestWarehouseSelectionStrategy -up-|> problems.Order_Inventory_Management_Sysyem_Zepto.WarehouseSelectionStrategy
  problems.Order_Inventory_Management_Sysyem_Zepto.Order o-- problems.Order_Inventory_Management_Sysyem_Zepto.Address : deliveryAddress
  problems.Order_Inventory_Management_Sysyem_Zepto.Order o-- problems.Order_Inventory_Management_Sysyem_Zepto.Invoice : invoice
  problems.Order_Inventory_Management_Sysyem_Zepto.Order o-- problems.Order_Inventory_Management_Sysyem_Zepto.OrderStatus : orderStatus
  problems.Order_Inventory_Management_Sysyem_Zepto.Order o-- problems.Order_Inventory_Management_Sysyem_Zepto.Payment : payment
  problems.Order_Inventory_Management_Sysyem_Zepto.Order o-- problems.Order_Inventory_Management_Sysyem_Zepto.User : user
  problems.Order_Inventory_Management_Sysyem_Zepto.Order o-- problems.Order_Inventory_Management_Sysyem_Zepto.Warehouse : warehouse
  problems.Order_Inventory_Management_Sysyem_Zepto.Payment o-- problems.Order_Inventory_Management_Sysyem_Zepto.PaymentMode : paymentMode
  problems.Order_Inventory_Management_Sysyem_Zepto.ProductDeliverySystem o-- problems.Order_Inventory_Management_Sysyem_Zepto.OrderController : orderController
  problems.Order_Inventory_Management_Sysyem_Zepto.ProductDeliverySystem o-- problems.Order_Inventory_Management_Sysyem_Zepto.UserController : userController
  problems.Order_Inventory_Management_Sysyem_Zepto.ProductDeliverySystem o-- problems.Order_Inventory_Management_Sysyem_Zepto.WarehouseController : warehouseController
  problems.Order_Inventory_Management_Sysyem_Zepto.UPIPaymentMode .up.|> problems.Order_Inventory_Management_Sysyem_Zepto.PaymentMode
  problems.Order_Inventory_Management_Sysyem_Zepto.User o-- problems.Order_Inventory_Management_Sysyem_Zepto.Address : address
  problems.Order_Inventory_Management_Sysyem_Zepto.User o-- problems.Order_Inventory_Management_Sysyem_Zepto.Cart : userCartDetails
  problems.Order_Inventory_Management_Sysyem_Zepto.Warehouse o-- problems.Order_Inventory_Management_Sysyem_Zepto.Address : address
  problems.Order_Inventory_Management_Sysyem_Zepto.Warehouse o-- problems.Order_Inventory_Management_Sysyem_Zepto.Inventory : inventory
  problems.Order_Inventory_Management_Sysyem_Zepto.WarehouseController o-- problems.Order_Inventory_Management_Sysyem_Zepto.WarehouseSelectionStrategy : warehouseSelectionStrategy
  problems.Undo_Redo.RemoteController o-- problems.Undo_Redo.ICommand : command
  problems.Undo_Redo.TurnOffACCommand .up.|> problems.Undo_Redo.ICommand
  problems.Undo_Redo.TurnOffACCommand o-- problems.Undo_Redo.AirConditioner : ac
  problems.Undo_Redo.TurnOnACCommand .up.|> problems.Undo_Redo.ICommand
  problems.Undo_Redo.TurnOnACCommand o-- problems.Undo_Redo.AirConditioner : ac


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
