@startuml

title __ABSTRACT_FACTORY's Class Diagram__\n

  namespace designPatterns.creational.abstract_factory {
    class designPatterns.creational.abstract_factory.LuxuryVehicle1 {
        + average()
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    class designPatterns.creational.abstract_factory.LuxuryVehicle2 {
        + average()
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    class designPatterns.creational.abstract_factory.LuxuryVehicleFactory {
        + getVehicle()
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    class designPatterns.creational.abstract_factory.Main {
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    class designPatterns.creational.abstract_factory.OrdinaryVehicle1 {
        + average()
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    class designPatterns.creational.abstract_factory.OrdinaryVehicle2 {
        + average()
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    class designPatterns.creational.abstract_factory.OrdinaryVehicleFactory {
        + getVehicle()
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    interface designPatterns.creational.abstract_factory.Vehicle {
        {abstract} + average()
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    interface designPatterns.creational.abstract_factory.VehicleFactory {
        {abstract} + getVehicle()
    }
  }
  

  namespace designPatterns.creational.abstract_factory {
    class designPatterns.creational.abstract_factory.VehicleFactoryProducer {
        {static} + getVehicleFactory()
    }
  }
  

  designPatterns.creational.abstract_factory.LuxuryVehicle1 .up.|> designPatterns.creational.abstract_factory.Vehicle
  designPatterns.creational.abstract_factory.LuxuryVehicle2 .up.|> designPatterns.creational.abstract_factory.Vehicle
  designPatterns.creational.abstract_factory.LuxuryVehicleFactory .up.|> designPatterns.creational.abstract_factory.VehicleFactory
  designPatterns.creational.abstract_factory.OrdinaryVehicle1 .up.|> designPatterns.creational.abstract_factory.Vehicle
  designPatterns.creational.abstract_factory.OrdinaryVehicle2 .up.|> designPatterns.creational.abstract_factory.Vehicle
  designPatterns.creational.abstract_factory.OrdinaryVehicleFactory .up.|> designPatterns.creational.abstract_factory.VehicleFactory


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
